# Note! If you're using jekyll serve --watch to run a server, you'll need to restart after any changes here
name: "Bioinformatics Support Unit"
description: "Bioinformatics research and support, for Newcastle University and beyond."
highlighter: pygments
baseurl: ""
#excerpt_separator: "<!--more-->"

owner: "Simon Cockell"
email: "bsu-support@ncl.ac.uk"
twitter: "sjcockell"
github: "sjcockell"
facebook: "sjcockell"
# the following really long number is what you find in https://plus.google.com/your-really-long-id/posts
googleplus: 114251972271434846418
location: |
    William Leech Building,
    Framlington Place
    Newcastle-upon-Tyne, NE2 4HH
    UK
phone: 0191 208 7253
skype: sjcockell
